//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package zajednicko.model.potvrda;

import zajednicko.model.BaseModel;
import zajednicko.model.CTpodaciVakcinisanog;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ftn.uns.ac.rs/zajednicka}STid"/&gt;
 *         &lt;element name="podaciVakcinisanog" type="{http://www.ftn.uns.ac.rs/zajednicka}CTpodaciVakcinisanog"/&gt;
 *         &lt;element name="podaciVakcinacije" type="{http://www.ftn.uns.ac.rs/potvrda-o-vakcinaciji}CTvakcinacijaPodaciPotvrda"/&gt;
 *         &lt;element name="QRKod" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="sifra" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciVakcinisanog",
    "podaciVakcinacije",
    "qrKod"
})
@XmlRootElement(name = "potvrdaVakcinacije")
public class PotvrdaVakcinacije extends BaseModel {

    @XmlElement(required = true)
    protected CTpodaciVakcinisanog podaciVakcinisanog;
    @XmlElement(required = true)
    protected CTvakcinacijaPodaciPotvrda podaciVakcinacije;
    @XmlElement(name = "QRKod", required = true)
    protected String qrKod;
    @XmlAttribute(name = "sifra", required = true)
    protected String sifra;

    /**
     * Gets the value of the podaciVakcinisanog property.
     * 
     * @return
     *     possible object is
     *     {@link CTpodaciVakcinisanog }
     *     
     */
    public CTpodaciVakcinisanog getPodaciVakcinisanog() {
        return podaciVakcinisanog;
    }

    /**
     * Sets the value of the podaciVakcinisanog property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTpodaciVakcinisanog }
     *     
     */
    public void setPodaciVakcinisanog(CTpodaciVakcinisanog value) {
        this.podaciVakcinisanog = value;
    }

    /**
     * Gets the value of the podaciVakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link CTvakcinacijaPodaciPotvrda }
     *     
     */
    public CTvakcinacijaPodaciPotvrda getPodaciVakcinacije() {
        return podaciVakcinacije;
    }

    /**
     * Sets the value of the podaciVakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTvakcinacijaPodaciPotvrda }
     *     
     */
    public void setPodaciVakcinacije(CTvakcinacijaPodaciPotvrda value) {
        this.podaciVakcinacije = value;
    }

    /**
     * Gets the value of the qrKod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQRKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQRKod(String value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the sifra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifra() {
        return sifra;
    }

    /**
     * Sets the value of the sifra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifra(String value) {
        this.sifra = value;
    }

}
