//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.obrazac_saglasnosti_bridge.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CTvrstaDrzavljanstva complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTvrstaDrzavljanstva"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="drzavljanstvoSrbije" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *           &lt;element name="jmbg" type="{http://www.ftn.uns.ac.rs/zajednicka}STjmbg"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="stranoDrzavljanstvo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *           &lt;choice&gt;
 *             &lt;element name="brojPasosa" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojPasosa"/&gt;
 *             &lt;element name="EBS" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojPasosa"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTvrstaDrzavljanstva", propOrder = {
    "drzavljanstvoSrbije",
    "jmbg",
    "stranoDrzavljanstvo",
    "brojPasosa",
    "ebs"
})
public class CTvrstaDrzavljanstva {

    protected Object drzavljanstvoSrbije;
    protected String jmbg;
    protected String stranoDrzavljanstvo;
    protected String brojPasosa;
    @XmlElement(name = "EBS")
    protected String ebs;

    /**
     * Gets the value of the drzavljanstvoSrbije property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDrzavljanstvoSrbije() {
        return drzavljanstvoSrbije;
    }

    /**
     * Sets the value of the drzavljanstvoSrbije property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDrzavljanstvoSrbije(Object value) {
        this.drzavljanstvoSrbije = value;
    }

    /**
     * Gets the value of the jmbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJmbg() {
        return jmbg;
    }

    /**
     * Sets the value of the jmbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJmbg(String value) {
        this.jmbg = value;
    }

    /**
     * Gets the value of the stranoDrzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStranoDrzavljanstvo() {
        return stranoDrzavljanstvo;
    }

    /**
     * Sets the value of the stranoDrzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStranoDrzavljanstvo(String value) {
        this.stranoDrzavljanstvo = value;
    }

    /**
     * Gets the value of the brojPasosa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPasosa() {
        return brojPasosa;
    }

    /**
     * Sets the value of the brojPasosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPasosa(String value) {
        this.brojPasosa = value;
    }

    /**
     * Gets the value of the ebs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEBS() {
        return ebs;
    }

    /**
     * Sets the value of the ebs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEBS(String value) {
        this.ebs = value;
    }

}
