//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.obrazac_saglasnosti_bridge.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vaccineisbackend.model.obrazac_saglasnosti package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vaccineisbackend.model.obrazac_saglasnosti
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije }
     * 
     */
    public CTevidencijaVakcinacije createCTevidencijaVakcinacije() {
        return new CTevidencijaVakcinacije();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.PodaciVakcinacija }
     * 
     */
    public CTevidencijaVakcinacije.PodaciVakcinacija createCTevidencijaVakcinacijePodaciVakcinacija() {
        return new CTevidencijaVakcinacije.PodaciVakcinacija();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije }
     * 
     */
    public CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije createCTevidencijaVakcinacijePodaciVakcinacijaPrivremeneKontraindikacije() {
        return new CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije();
    }

    /**
     * Create an instance of {@link CTpacijentSaglasnost }
     * 
     */
    public CTpacijentSaglasnost createCTpacijentSaglasnost() {
        return new CTpacijentSaglasnost();
    }

    /**
     * Create an instance of {@link Saglasnost }
     * 
     */
    public Saglasnost createSaglasnost() {
        return new Saglasnost();
    }

    /**
     * Create an instance of {@link CTvrstaDrzavljanstva }
     * 
     */
    public CTvrstaDrzavljanstva createCTvrstaDrzavljanstva() {
        return new CTvrstaDrzavljanstva();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.ZdravstvenaUstanova }
     * 
     */
    public CTevidencijaVakcinacije.ZdravstvenaUstanova createCTevidencijaVakcinacijeZdravstvenaUstanova() {
        return new CTevidencijaVakcinacije.ZdravstvenaUstanova();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.PodaciLjekara }
     * 
     */
    public CTevidencijaVakcinacije.PodaciLjekara createCTevidencijaVakcinacijePodaciLjekara() {
        return new CTevidencijaVakcinacije.PodaciLjekara();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.PodaciVakcinacija.Vakcinacija }
     * 
     */
    public CTevidencijaVakcinacije.PodaciVakcinacija.Vakcinacija createCTevidencijaVakcinacijePodaciVakcinacijaVakcinacija() {
        return new CTevidencijaVakcinacije.PodaciVakcinacija.Vakcinacija();
    }

    /**
     * Create an instance of {@link CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije.Kontraindikacija }
     * 
     */
    public CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije.Kontraindikacija createCTevidencijaVakcinacijePodaciVakcinacijaPrivremeneKontraindikacijeKontraindikacija() {
        return new CTevidencijaVakcinacije.PodaciVakcinacija.PrivremeneKontraindikacije.Kontraindikacija();
    }

    /**
     * Create an instance of {@link CTpacijentSaglasnost.PodaciMjesta }
     * 
     */
    public CTpacijentSaglasnost.PodaciMjesta createCTpacijentSaglasnostPodaciMjesta() {
        return new CTpacijentSaglasnost.PodaciMjesta();
    }

    /**
     * Create an instance of {@link CTpacijentSaglasnost.SocijalnaZastita }
     * 
     */
    public CTpacijentSaglasnost.SocijalnaZastita createCTpacijentSaglasnostSocijalnaZastita() {
        return new CTpacijentSaglasnost.SocijalnaZastita();
    }

    /**
     * Create an instance of {@link CTpacijentSaglasnost.IzjavaSaglasnosti }
     * 
     */
    public CTpacijentSaglasnost.IzjavaSaglasnosti createCTpacijentSaglasnostIzjavaSaglasnosti() {
        return new CTpacijentSaglasnost.IzjavaSaglasnosti();
    }

}
