//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.obrazac_saglasnosti_bridge.model;

import zajednicko.model.BaseModel;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="drzavljanstvo" type="{http://www.ftn.uns.ac.rs/obrazac-saglasnosti}CTvrstaDrzavljanstva"/&gt;
 *         &lt;element name="podaciPacijenta" type="{http://www.ftn.uns.ac.rs/obrazac-saglasnosti}CTpacijentSaglasnost"/&gt;
 *         &lt;element name="evidencijaVakcinacije" type="{http://www.ftn.uns.ac.rs/obrazac-saglasnosti}CTevidencijaVakcinacije"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "drzavljanstvo",
    "podaciPacijenta",
    "evidencijaVakcinacije"
})
@XmlRootElement(name = "saglasnost")
public class Saglasnost extends BaseModel {

    @XmlElement(required = true)
    protected CTvrstaDrzavljanstva drzavljanstvo;
    @XmlElement(required = true)
    protected CTpacijentSaglasnost podaciPacijenta;
    @XmlElement(required = true)
    protected CTevidencijaVakcinacije evidencijaVakcinacije;

    /**
     * Gets the value of the drzavljanstvo property.
     * 
     * @return
     *     possible object is
     *     {@link CTvrstaDrzavljanstva }
     *     
     */
    public CTvrstaDrzavljanstva getDrzavljanstvo() {
        return drzavljanstvo;
    }

    /**
     * Sets the value of the drzavljanstvo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTvrstaDrzavljanstva }
     *     
     */
    public void setDrzavljanstvo(CTvrstaDrzavljanstva value) {
        this.drzavljanstvo = value;
    }

    /**
     * Gets the value of the podaciPacijenta property.
     * 
     * @return
     *     possible object is
     *     {@link CTpacijentSaglasnost }
     *     
     */
    public CTpacijentSaglasnost getPodaciPacijenta() {
        return podaciPacijenta;
    }

    /**
     * Sets the value of the podaciPacijenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTpacijentSaglasnost }
     *     
     */
    public void setPodaciPacijenta(CTpacijentSaglasnost value) {
        this.podaciPacijenta = value;
    }

    /**
     * Gets the value of the evidencijaVakcinacije property.
     * 
     * @return
     *     possible object is
     *     {@link CTevidencijaVakcinacije }
     *     
     */
    public CTevidencijaVakcinacije getEvidencijaVakcinacije() {
        return evidencijaVakcinacije;
    }

    /**
     * Sets the value of the evidencijaVakcinacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTevidencijaVakcinacije }
     *     
     */
    public void setEvidencijaVakcinacije(CTevidencijaVakcinacije value) {
        this.evidencijaVakcinacije = value;
    }

}
