//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.obrazac_saglasnosti_bridge.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STradniStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="STradniStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="запослен"/&gt;
 *     &lt;enumeration value="незапослен"/&gt;
 *     &lt;enumeration value="пензионер"/&gt;
 *     &lt;enumeration value="ученик"/&gt;
 *     &lt;enumeration value="студент"/&gt;
 *     &lt;enumeration value="дете"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "STradniStatus")
@XmlEnum
public enum STradniStatus {

    @XmlEnumValue("\u0437\u0430\u043f\u043e\u0441\u043b\u0435\u043d")
    ЗАПОСЛЕН("\u0437\u0430\u043f\u043e\u0441\u043b\u0435\u043d"),
    @XmlEnumValue("\u043d\u0435\u0437\u0430\u043f\u043e\u0441\u043b\u0435\u043d")
    НЕЗАПОСЛЕН("\u043d\u0435\u0437\u0430\u043f\u043e\u0441\u043b\u0435\u043d"),
    @XmlEnumValue("\u043f\u0435\u043d\u0437\u0438\u043e\u043d\u0435\u0440")
    ПЕНЗИОНЕР("\u043f\u0435\u043d\u0437\u0438\u043e\u043d\u0435\u0440"),
    @XmlEnumValue("\u0443\u0447\u0435\u043d\u0438\u043a")
    УЧЕНИК("\u0443\u0447\u0435\u043d\u0438\u043a"),
    @XmlEnumValue("\u0441\u0442\u0443\u0434\u0435\u043d\u0442")
    СТУДЕНТ("\u0441\u0442\u0443\u0434\u0435\u043d\u0442"),
    @XmlEnumValue("\u0434\u0435\u0442\u0435")
    ДЕТЕ("\u0434\u0435\u0442\u0435");
    private final String value;

    STradniStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STradniStatus fromValue(String v) {
        for (STradniStatus c: STradniStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
