//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package zajednicko.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zajednicka package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zajednicka
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CTpodaciVakcinisanog }
     * 
     */
    public CTpodaciVakcinisanog createCTpodaciVakcinisanog() {
        return new CTpodaciVakcinisanog();
    }

    /**
     * Create an instance of {@link CTadresa }
     * 
     */
    public CTadresa createCTadresa() {
        return new CTadresa();
    }

    /**
     * Create an instance of {@link CTlicniPodaci }
     * 
     */
    public CTlicniPodaci createCTlicniPodaci() {
        return new CTlicniPodaci();
    }

    /**
     * Create an instance of {@link CTpodnosilacZahtjeva }
     * 
     */
    public CTpodnosilacZahtjeva createCTpodnosilacZahtjeva() {
        return new CTpodnosilacZahtjeva();
    }

    /**
     * Create an instance of {@link CTvakcinacijaPodaci }
     * 
     */
    public CTvakcinacijaPodaci createCTvakcinacijaPodaci() {
        return new CTvakcinacijaPodaci();
    }

    /**
     * Create an instance of {@link CTkontakt }
     * 
     */
    public CTkontakt createCTkontakt() {
        return new CTkontakt();
    }

}
