//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package zajednicko.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STpol.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="STpol"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Мушко"/&gt;
 *     &lt;enumeration value="Женско"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "STpol")
@XmlEnum
public enum STpol {

    @XmlEnumValue("\u041c\u0443\u0448\u043a\u043e")
    МУШКО("\u041c\u0443\u0448\u043a\u043e"),
    @XmlEnumValue("\u0416\u0435\u043d\u0441\u043a\u043e")
    ЖЕНСКО("\u0416\u0435\u043d\u0441\u043a\u043e");
    private final String value;

    STpol(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STpol fromValue(String v) {
        for (STpol c: STpol.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
