//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 04:19:01 PM CET 
//


package vaccineisbackend.model.izvjestaj;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="period"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="pocetakPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                   &lt;element name="krajPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brojInteresovanjaImunizacija" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *         &lt;element name="sertifikatInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="brojZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *                   &lt;element name="izdatoZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *         &lt;element name="dozeVakcinaInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="dozaInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                             &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="raspodjelaDoza"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="tipVakcineInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datumIzdavanjaIzvjestaja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "period",
    "brojInteresovanjaImunizacija",
    "sertifikatInfo",
    "brojDoza",
    "dozeVakcinaInfo",
    "raspodjelaDoza",
    "datumIzdavanjaIzvjestaja"
})
@XmlRootElement(name = "izvjestaj")
public class Izvjestaj {

    @XmlElement(required = true)
    protected Izvjestaj.Period period;
    protected int brojInteresovanjaImunizacija;
    @XmlElement(required = true)
    protected Izvjestaj.SertifikatInfo sertifikatInfo;
    protected int brojDoza;
    @XmlElement(required = true)
    protected Izvjestaj.DozeVakcinaInfo dozeVakcinaInfo;
    @XmlElement(required = true)
    protected Izvjestaj.RaspodjelaDoza raspodjelaDoza;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanjaIzvjestaja;

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Izvjestaj.Period }
     *     
     */
    public Izvjestaj.Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvjestaj.Period }
     *     
     */
    public void setPeriod(Izvjestaj.Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the brojInteresovanjaImunizacija property.
     * 
     */
    public int getBrojInteresovanjaImunizacija() {
        return brojInteresovanjaImunizacija;
    }

    /**
     * Sets the value of the brojInteresovanjaImunizacija property.
     * 
     */
    public void setBrojInteresovanjaImunizacija(int value) {
        this.brojInteresovanjaImunizacija = value;
    }

    /**
     * Gets the value of the sertifikatInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Izvjestaj.SertifikatInfo }
     *     
     */
    public Izvjestaj.SertifikatInfo getSertifikatInfo() {
        return sertifikatInfo;
    }

    /**
     * Sets the value of the sertifikatInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvjestaj.SertifikatInfo }
     *     
     */
    public void setSertifikatInfo(Izvjestaj.SertifikatInfo value) {
        this.sertifikatInfo = value;
    }

    /**
     * Gets the value of the brojDoza property.
     * 
     */
    public int getBrojDoza() {
        return brojDoza;
    }

    /**
     * Sets the value of the brojDoza property.
     * 
     */
    public void setBrojDoza(int value) {
        this.brojDoza = value;
    }

    /**
     * Gets the value of the dozeVakcinaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Izvjestaj.DozeVakcinaInfo }
     *     
     */
    public Izvjestaj.DozeVakcinaInfo getDozeVakcinaInfo() {
        return dozeVakcinaInfo;
    }

    /**
     * Sets the value of the dozeVakcinaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvjestaj.DozeVakcinaInfo }
     *     
     */
    public void setDozeVakcinaInfo(Izvjestaj.DozeVakcinaInfo value) {
        this.dozeVakcinaInfo = value;
    }

    /**
     * Gets the value of the raspodjelaDoza property.
     * 
     * @return
     *     possible object is
     *     {@link Izvjestaj.RaspodjelaDoza }
     *     
     */
    public Izvjestaj.RaspodjelaDoza getRaspodjelaDoza() {
        return raspodjelaDoza;
    }

    /**
     * Sets the value of the raspodjelaDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvjestaj.RaspodjelaDoza }
     *     
     */
    public void setRaspodjelaDoza(Izvjestaj.RaspodjelaDoza value) {
        this.raspodjelaDoza = value;
    }

    /**
     * Gets the value of the datumIzdavanjaIzvjestaja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanjaIzvjestaja() {
        return datumIzdavanjaIzvjestaja;
    }

    /**
     * Sets the value of the datumIzdavanjaIzvjestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanjaIzvjestaja(XMLGregorianCalendar value) {
        this.datumIzdavanjaIzvjestaja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="dozaInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                   &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dozaInfo"
    })
    public static class DozeVakcinaInfo {

        protected List<Izvjestaj.DozeVakcinaInfo.DozaInfo> dozaInfo;

        /**
         * Gets the value of the dozaInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dozaInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDozaInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Izvjestaj.DozeVakcinaInfo.DozaInfo }
         * 
         * 
         */
        public List<Izvjestaj.DozeVakcinaInfo.DozaInfo> getDozaInfo() {
            if (dozaInfo == null) {
                dozaInfo = new ArrayList<Izvjestaj.DozeVakcinaInfo.DozaInfo>();
            }
            return this.dozaInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *         &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "redniBrojDoze",
            "brojDatihDoza"
        })
        public static class DozaInfo {

            protected int redniBrojDoze;
            protected int brojDatihDoza;

            /**
             * Gets the value of the redniBrojDoze property.
             * 
             */
            public int getRedniBrojDoze() {
                return redniBrojDoze;
            }

            /**
             * Sets the value of the redniBrojDoze property.
             * 
             */
            public void setRedniBrojDoze(int value) {
                this.redniBrojDoze = value;
            }

            /**
             * Gets the value of the brojDatihDoza property.
             * 
             */
            public int getBrojDatihDoza() {
                return brojDatihDoza;
            }

            /**
             * Sets the value of the brojDatihDoza property.
             * 
             */
            public void setBrojDatihDoza(int value) {
                this.brojDatihDoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="pocetakPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *         &lt;element name="krajPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pocetakPerioda",
        "krajPerioda"
    })
    public static class Period {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar pocetakPerioda;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar krajPerioda;

        /**
         * Gets the value of the pocetakPerioda property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPocetakPerioda() {
            return pocetakPerioda;
        }

        /**
         * Sets the value of the pocetakPerioda property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPocetakPerioda(XMLGregorianCalendar value) {
            this.pocetakPerioda = value;
        }

        /**
         * Gets the value of the krajPerioda property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getKrajPerioda() {
            return krajPerioda;
        }

        /**
         * Sets the value of the krajPerioda property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setKrajPerioda(XMLGregorianCalendar value) {
            this.krajPerioda = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="tipVakcineInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipVakcineInfo"
    })
    public static class RaspodjelaDoza {

        @XmlElement(required = true)
        protected List<Izvjestaj.RaspodjelaDoza.TipVakcineInfo> tipVakcineInfo;

        /**
         * Gets the value of the tipVakcineInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tipVakcineInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTipVakcineInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Izvjestaj.RaspodjelaDoza.TipVakcineInfo }
         * 
         * 
         */
        public List<Izvjestaj.RaspodjelaDoza.TipVakcineInfo> getTipVakcineInfo() {
            if (tipVakcineInfo == null) {
                tipVakcineInfo = new ArrayList<Izvjestaj.RaspodjelaDoza.TipVakcineInfo>();
            }
            return this.tipVakcineInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivProizvodjaca",
            "brojDoza"
        })
        public static class TipVakcineInfo {

            @XmlElement(required = true)
            protected String nazivProizvodjaca;
            protected int brojDoza;

            /**
             * Gets the value of the nazivProizvodjaca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivProizvodjaca() {
                return nazivProizvodjaca;
            }

            /**
             * Sets the value of the nazivProizvodjaca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivProizvodjaca(String value) {
                this.nazivProizvodjaca = value;
            }

            /**
             * Gets the value of the brojDoza property.
             * 
             */
            public int getBrojDoza() {
                return brojDoza;
            }

            /**
             * Sets the value of the brojDoza property.
             * 
             */
            public void setBrojDoza(int value) {
                this.brojDoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="brojZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
     *         &lt;element name="izdatoZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojZahtjeva",
        "izdatoZahtjeva"
    })
    public static class SertifikatInfo {

        protected int brojZahtjeva;
        protected int izdatoZahtjeva;

        /**
         * Gets the value of the brojZahtjeva property.
         * 
         */
        public int getBrojZahtjeva() {
            return brojZahtjeva;
        }

        /**
         * Sets the value of the brojZahtjeva property.
         * 
         */
        public void setBrojZahtjeva(int value) {
            this.brojZahtjeva = value;
        }

        /**
         * Gets the value of the izdatoZahtjeva property.
         * 
         */
        public int getIzdatoZahtjeva() {
            return izdatoZahtjeva;
        }

        /**
         * Sets the value of the izdatoZahtjeva property.
         * 
         */
        public void setIzdatoZahtjeva(int value) {
            this.izdatoZahtjeva = value;
        }

    }

}
