//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.zahtev_sertifikata_bridge.model;

import zajednicko.model.BaseModel;
import zajednicko.model.CTpodnosilacZahtjeva;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="podnosilac" type="{http://www.ftn.uns.ac.rs/zajednicka}CTpodnosilacZahtjeva"/&gt;
 *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mjestoDatum"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lokacija" type="{http://www.ftn.uns.ac.rs/zajednicka}STlokacija"/&gt;
 *                   &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podnosilac",
    "razlog",
    "mjestoDatum"
})
@XmlRootElement(name = "zahtjev")
public class Zahtjev extends BaseModel {

    @XmlElement(required = true)
    protected CTpodnosilacZahtjeva podnosilac;
    @XmlElement(required = true)
    protected String razlog;
    @XmlElement(required = true)
    protected MjestoDatum mjestoDatum;

    /**
     * Gets the value of the podnosilac property.
     * 
     * @return
     *     possible object is
     *     {@link CTpodnosilacZahtjeva }
     *     
     */
    public CTpodnosilacZahtjeva getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link CTpodnosilacZahtjeva }
     *     
     */
    public void setPodnosilac(CTpodnosilacZahtjeva value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the razlog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazlog() {
        return razlog;
    }

    /**
     * Sets the value of the razlog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazlog(String value) {
        this.razlog = value;
    }

    /**
     * Gets the value of the mjestoDatum property.
     * 
     * @return
     *     possible object is
     *     {@link MjestoDatum }
     *     
     */
    public MjestoDatum getMjestoDatum() {
        return mjestoDatum;
    }

    /**
     * Sets the value of the mjestoDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link MjestoDatum }
     *     
     */
    public void setMjestoDatum(MjestoDatum value) {
        this.mjestoDatum = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lokacija" type="{http://www.ftn.uns.ac.rs/zajednicka}STlokacija"/&gt;
     *         &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lokacija",
        "datum"
    })
    public static class MjestoDatum {

        @XmlElement(required = true)
        protected String lokacija;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datum;

        /**
         * Gets the value of the lokacija property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLokacija() {
            return lokacija;
        }

        /**
         * Sets the value of the lokacija property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLokacija(String value) {
            this.lokacija = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatum(XMLGregorianCalendar value) {
            this.datum = value;
        }

    }

}
