//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisportal.obrazac_saglasnosti.model;

import zajednicko.model.STtipVakcine;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CTevidencijaVakcinacije complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTevidencijaVakcinacije"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="zdravstvenaUstanova"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="nazivZdravstveneUstanove" type="{http://www.ftn.uns.ac.rs/zajednicka}STnazivZdravstveneUstanove"/&gt;
 *                   &lt;element name="vakcinacijskiPunkt" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podaciLjekara"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ime" type="{http://www.ftn.uns.ac.rs/zajednicka}STime"/&gt;
 *                   &lt;element name="prezime" type="{http://www.ftn.uns.ac.rs/zajednicka}STprezime"/&gt;
 *                   &lt;element name="faksimil" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                   &lt;element name="brojTelefona" type="{http://www.ftn.uns.ac.rs/zajednicka}STmobilniTelefon"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="podaciVakcinacija"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence maxOccurs="unbounded"&gt;
 *                     &lt;element name="vakcinacija"&gt;
 *                       &lt;complexType&gt;
 *                         &lt;complexContent&gt;
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="nazivVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STtipVakcine"/&gt;
 *                               &lt;element name="datumDavanjaVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                               &lt;element name="nacinDavanjaVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                               &lt;element name="ekstremitet"&gt;
 *                                 &lt;simpleType&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                     &lt;enumeration value="Десна рука"/&gt;
 *                                     &lt;enumeration value="Лијева рука"/&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/simpleType&gt;
 *                               &lt;/element&gt;
 *                               &lt;element name="serijaVakcine" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *                               &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                               &lt;element name="nezeljenaReakcija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                               &lt;element name="potpisLjekara" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/restriction&gt;
 *                         &lt;/complexContent&gt;
 *                       &lt;/complexType&gt;
 *                     &lt;/element&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="privremeneKontraindikacije" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                             &lt;element name="kontraindikacija"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="datumUtvrdjivanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                                       &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="odlukaKomisije"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Да"/&gt;
 *                         &lt;enumeration value="Не"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTevidencijaVakcinacije", propOrder = {
    "zdravstvenaUstanova",
    "podaciLjekara",
    "podaciVakcinacija"
})
public class CTevidencijaVakcinacije {

    @XmlElement(required = true)
    protected ZdravstvenaUstanova zdravstvenaUstanova;
    @XmlElement(required = true)
    protected PodaciLjekara podaciLjekara;
    @XmlElement(required = true)
    protected PodaciVakcinacija podaciVakcinacija;

    /**
     * Gets the value of the zdravstvenaUstanova property.
     * 
     * @return
     *     possible object is
     *     {@link ZdravstvenaUstanova }
     *     
     */
    public ZdravstvenaUstanova getZdravstvenaUstanova() {
        return zdravstvenaUstanova;
    }

    /**
     * Sets the value of the zdravstvenaUstanova property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZdravstvenaUstanova }
     *     
     */
    public void setZdravstvenaUstanova(ZdravstvenaUstanova value) {
        this.zdravstvenaUstanova = value;
    }

    /**
     * Gets the value of the podaciLjekara property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciLjekara }
     *     
     */
    public PodaciLjekara getPodaciLjekara() {
        return podaciLjekara;
    }

    /**
     * Sets the value of the podaciLjekara property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciLjekara }
     *     
     */
    public void setPodaciLjekara(PodaciLjekara value) {
        this.podaciLjekara = value;
    }

    /**
     * Gets the value of the podaciVakcinacija property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciVakcinacija }
     *     
     */
    public PodaciVakcinacija getPodaciVakcinacija() {
        return podaciVakcinacija;
    }

    /**
     * Sets the value of the podaciVakcinacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciVakcinacija }
     *     
     */
    public void setPodaciVakcinacija(PodaciVakcinacija value) {
        this.podaciVakcinacija = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ime" type="{http://www.ftn.uns.ac.rs/zajednicka}STime"/&gt;
     *         &lt;element name="prezime" type="{http://www.ftn.uns.ac.rs/zajednicka}STprezime"/&gt;
     *         &lt;element name="faksimil" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *         &lt;element name="brojTelefona" type="{http://www.ftn.uns.ac.rs/zajednicka}STmobilniTelefon"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "faksimil",
        "brojTelefona"
    })
    public static class PodaciLjekara {

        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        protected Object faksimil;
        @XmlElement(required = true)
        protected String brojTelefona;

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the faksimil property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getFaksimil() {
            return faksimil;
        }

        /**
         * Sets the value of the faksimil property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setFaksimil(Object value) {
            this.faksimil = value;
        }

        /**
         * Gets the value of the brojTelefona property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrojTelefona() {
            return brojTelefona;
        }

        /**
         * Sets the value of the brojTelefona property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrojTelefona(String value) {
            this.brojTelefona = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence maxOccurs="unbounded"&gt;
     *           &lt;element name="vakcinacija"&gt;
     *             &lt;complexType&gt;
     *               &lt;complexContent&gt;
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="nazivVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STtipVakcine"/&gt;
     *                     &lt;element name="datumDavanjaVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *                     &lt;element name="nacinDavanjaVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                     &lt;element name="ekstremitet"&gt;
     *                       &lt;simpleType&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                           &lt;enumeration value="Десна рука"/&gt;
     *                           &lt;enumeration value="Лијева рука"/&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/simpleType&gt;
     *                     &lt;/element&gt;
     *                     &lt;element name="serijaVakcine" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *                     &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                     &lt;element name="nezeljenaReakcija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                     &lt;element name="potpisLjekara" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/restriction&gt;
     *               &lt;/complexContent&gt;
     *             &lt;/complexType&gt;
     *           &lt;/element&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="privremeneKontraindikacije" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *                   &lt;element name="kontraindikacija"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="datumUtvrdjivanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *                             &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="odlukaKomisije"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Да"/&gt;
     *               &lt;enumeration value="Не"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vakcinacija",
        "privremeneKontraindikacije",
        "odlukaKomisije"
    })
    public static class PodaciVakcinacija {

        @XmlElement(required = true)
        protected List<Vakcinacija> vakcinacija;
        protected PrivremeneKontraindikacije privremeneKontraindikacije;
        @XmlElement(required = true)
        protected String odlukaKomisije;

        /**
         * Gets the value of the vakcinacija property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vakcinacija property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVakcinacija().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Vakcinacija }
         * 
         * 
         */
        public List<Vakcinacija> getVakcinacija() {
            if (vakcinacija == null) {
                vakcinacija = new ArrayList<Vakcinacija>();
            }
            return this.vakcinacija;
        }

        /**
         * Gets the value of the privremeneKontraindikacije property.
         * 
         * @return
         *     possible object is
         *     {@link PrivremeneKontraindikacije }
         *     
         */
        public PrivremeneKontraindikacije getPrivremeneKontraindikacije() {
            return privremeneKontraindikacije;
        }

        /**
         * Sets the value of the privremeneKontraindikacije property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrivremeneKontraindikacije }
         *     
         */
        public void setPrivremeneKontraindikacije(PrivremeneKontraindikacije value) {
            this.privremeneKontraindikacije = value;
        }

        /**
         * Gets the value of the odlukaKomisije property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOdlukaKomisije() {
            return odlukaKomisije;
        }

        /**
         * Sets the value of the odlukaKomisije property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOdlukaKomisije(String value) {
            this.odlukaKomisije = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
         *         &lt;element name="kontraindikacija"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="datumUtvrdjivanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
         *                   &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kontraindikacija"
        })
        public static class PrivremeneKontraindikacije {

            protected List<Kontraindikacija> kontraindikacija;

            /**
             * Gets the value of the kontraindikacija property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the kontraindikacija property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getKontraindikacija().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Kontraindikacija }
             * 
             * 
             */
            public List<Kontraindikacija> getKontraindikacija() {
                if (kontraindikacija == null) {
                    kontraindikacija = new ArrayList<Kontraindikacija>();
                }
                return this.kontraindikacija;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="datumUtvrdjivanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
             *         &lt;element name="dijagnoza" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "datumUtvrdjivanja",
                "dijagnoza"
            })
            public static class Kontraindikacija {

                @XmlElement(required = true)
                @XmlSchemaType(name = "date")
                protected XMLGregorianCalendar datumUtvrdjivanja;
                @XmlElement(required = true)
                protected String dijagnoza;

                /**
                 * Gets the value of the datumUtvrdjivanja property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getDatumUtvrdjivanja() {
                    return datumUtvrdjivanja;
                }

                /**
                 * Sets the value of the datumUtvrdjivanja property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setDatumUtvrdjivanja(XMLGregorianCalendar value) {
                    this.datumUtvrdjivanja = value;
                }

                /**
                 * Gets the value of the dijagnoza property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDijagnoza() {
                    return dijagnoza;
                }

                /**
                 * Sets the value of the dijagnoza property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDijagnoza(String value) {
                    this.dijagnoza = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nazivVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STtipVakcine"/&gt;
         *         &lt;element name="datumDavanjaVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
         *         &lt;element name="nacinDavanjaVakcine" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="ekstremitet"&gt;
         *           &lt;simpleType&gt;
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *               &lt;enumeration value="Десна рука"/&gt;
         *               &lt;enumeration value="Лијева рука"/&gt;
         *             &lt;/restriction&gt;
         *           &lt;/simpleType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="serijaVakcine" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
         *         &lt;element name="proizvodjac" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="nezeljenaReakcija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="potpisLjekara" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivVakcine",
            "datumDavanjaVakcine",
            "nacinDavanjaVakcine",
            "ekstremitet",
            "serijaVakcine",
            "proizvodjac",
            "nezeljenaReakcija",
            "potpisLjekara"
        })
        public static class Vakcinacija {

            @XmlElement(required = true)
            @XmlSchemaType(name = "string")
            protected STtipVakcine nazivVakcine;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar datumDavanjaVakcine;
            @XmlElement(required = true)
            protected String nacinDavanjaVakcine;
            @XmlElement(required = true)
            protected String ekstremitet;
            @XmlElement(required = true)
            protected Object serijaVakcine;
            @XmlElement(required = true)
            protected String proizvodjac;
            protected String nezeljenaReakcija;
            protected Object potpisLjekara;

            /**
             * Gets the value of the nazivVakcine property.
             * 
             * @return
             *     possible object is
             *     {@link STtipVakcine }
             *     
             */
            public STtipVakcine getNazivVakcine() {
                return nazivVakcine;
            }

            /**
             * Sets the value of the nazivVakcine property.
             * 
             * @param value
             *     allowed object is
             *     {@link STtipVakcine }
             *     
             */
            public void setNazivVakcine(STtipVakcine value) {
                this.nazivVakcine = value;
            }

            /**
             * Gets the value of the datumDavanjaVakcine property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatumDavanjaVakcine() {
                return datumDavanjaVakcine;
            }

            /**
             * Sets the value of the datumDavanjaVakcine property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatumDavanjaVakcine(XMLGregorianCalendar value) {
                this.datumDavanjaVakcine = value;
            }

            /**
             * Gets the value of the nacinDavanjaVakcine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNacinDavanjaVakcine() {
                return nacinDavanjaVakcine;
            }

            /**
             * Sets the value of the nacinDavanjaVakcine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNacinDavanjaVakcine(String value) {
                this.nacinDavanjaVakcine = value;
            }

            /**
             * Gets the value of the ekstremitet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEkstremitet() {
                return ekstremitet;
            }

            /**
             * Sets the value of the ekstremitet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEkstremitet(String value) {
                this.ekstremitet = value;
            }

            /**
             * Gets the value of the serijaVakcine property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getSerijaVakcine() {
                return serijaVakcine;
            }

            /**
             * Sets the value of the serijaVakcine property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setSerijaVakcine(Object value) {
                this.serijaVakcine = value;
            }

            /**
             * Gets the value of the proizvodjac property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProizvodjac() {
                return proizvodjac;
            }

            /**
             * Sets the value of the proizvodjac property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProizvodjac(String value) {
                this.proizvodjac = value;
            }

            /**
             * Gets the value of the nezeljenaReakcija property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNezeljenaReakcija() {
                return nezeljenaReakcija;
            }

            /**
             * Sets the value of the nezeljenaReakcija property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNezeljenaReakcija(String value) {
                this.nezeljenaReakcija = value;
            }

            /**
             * Gets the value of the potpisLjekara property.
             * 
             * @return
             *     possible object is
             *     {@link Object }
             *     
             */
            public Object getPotpisLjekara() {
                return potpisLjekara;
            }

            /**
             * Sets the value of the potpisLjekara property.
             * 
             * @param value
             *     allowed object is
             *     {@link Object }
             *     
             */
            public void setPotpisLjekara(Object value) {
                this.potpisLjekara = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="nazivZdravstveneUstanove" type="{http://www.ftn.uns.ac.rs/zajednicka}STnazivZdravstveneUstanove"/&gt;
     *         &lt;element name="vakcinacijskiPunkt" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivZdravstveneUstanove",
        "vakcinacijskiPunkt"
    })
    public static class ZdravstvenaUstanova {

        @XmlElement(required = true)
        protected String nazivZdravstveneUstanove;
        @XmlElement(required = true)
        protected Object vakcinacijskiPunkt;

        /**
         * Gets the value of the nazivZdravstveneUstanove property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivZdravstveneUstanove() {
            return nazivZdravstveneUstanove;
        }

        /**
         * Sets the value of the nazivZdravstveneUstanove property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivZdravstveneUstanove(String value) {
            this.nazivZdravstveneUstanove = value;
        }

        /**
         * Gets the value of the vakcinacijskiPunkt property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getVakcinacijskiPunkt() {
            return vakcinacijskiPunkt;
        }

        /**
         * Sets the value of the vakcinacijskiPunkt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setVakcinacijskiPunkt(Object value) {
            this.vakcinacijskiPunkt = value;
        }

    }

}
