//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisportal.obrazac_saglasnosti.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for STzanimanje.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="STzanimanje"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="здравствена заштита"/&gt;
 *     &lt;enumeration value="социјална заштита"/&gt;
 *     &lt;enumeration value="просвјета"/&gt;
 *     &lt;enumeration value="МУП"/&gt;
 *     &lt;enumeration value="Војска РС"/&gt;
 *     &lt;enumeration value="друго"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "STzanimanje")
@XmlEnum
public enum STzanimanje {

    @XmlEnumValue("\u0437\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0435\u043d\u0430 \u0437\u0430\u0448\u0442\u0438\u0442\u0430")
    ЗДРАВСТВЕНА_ЗАШТИТА("\u0437\u0434\u0440\u0430\u0432\u0441\u0442\u0432\u0435\u043d\u0430 \u0437\u0430\u0448\u0442\u0438\u0442\u0430"),
    @XmlEnumValue("\u0441\u043e\u0446\u0438\u0458\u0430\u043b\u043d\u0430 \u0437\u0430\u0448\u0442\u0438\u0442\u0430")
    СОЦИЈАЛНА_ЗАШТИТА("\u0441\u043e\u0446\u0438\u0458\u0430\u043b\u043d\u0430 \u0437\u0430\u0448\u0442\u0438\u0442\u0430"),
    @XmlEnumValue("\u043f\u0440\u043e\u0441\u0432\u0458\u0435\u0442\u0430")
    ПРОСВЈЕТА("\u043f\u0440\u043e\u0441\u0432\u0458\u0435\u0442\u0430"),
    МУП("\u041c\u0423\u041f"),
    @XmlEnumValue("\u0412\u043e\u0458\u0441\u043a\u0430 \u0420\u0421")
    ВОЈСКА_РС("\u0412\u043e\u0458\u0441\u043a\u0430 \u0420\u0421"),
    @XmlEnumValue("\u0434\u0440\u0443\u0433\u043e")
    ДРУГО("\u0434\u0440\u0443\u0433\u043e");
    private final String value;

    STzanimanje(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static STzanimanje fromValue(String v) {
        for (STzanimanje c: STzanimanje.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
