//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.digitalni_sertifikat.model;

import zajednicko.model.CTadresa;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CTinfoSertifikata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTinfoSertifikata"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="izdavacSertifikata"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="digitalniPotpis"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="nazivUstanove" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="adresaUstanove" type="{http://www.ftn.uns.ac.rs/zajednicka}CTadresa"/&gt;
 *                   &lt;element name="datumIzdavanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTinfoSertifikata", propOrder = {

})
public class CTinfoSertifikata {

    @XmlElement(required = true)
    protected String izdavacSertifikata;
    @XmlElement(required = true)
    protected DigitalniPotpis digitalniPotpis;

    /**
     * Gets the value of the izdavacSertifikata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIzdavacSertifikata() {
        return izdavacSertifikata;
    }

    /**
     * Sets the value of the izdavacSertifikata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIzdavacSertifikata(String value) {
        this.izdavacSertifikata = value;
    }

    /**
     * Gets the value of the digitalniPotpis property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalniPotpis }
     *     
     */
    public DigitalniPotpis getDigitalniPotpis() {
        return digitalniPotpis;
    }

    /**
     * Sets the value of the digitalniPotpis property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalniPotpis }
     *     
     */
    public void setDigitalniPotpis(DigitalniPotpis value) {
        this.digitalniPotpis = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="nazivUstanove" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="adresaUstanove" type="{http://www.ftn.uns.ac.rs/zajednicka}CTadresa"/&gt;
     *         &lt;element name="datumIzdavanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nazivUstanove",
        "adresaUstanove",
        "datumIzdavanja"
    })
    public static class DigitalniPotpis {

        @XmlElement(required = true)
        protected String nazivUstanove;
        @XmlElement(required = true)
        protected CTadresa adresaUstanove;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar datumIzdavanja;

        /**
         * Gets the value of the nazivUstanove property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivUstanove() {
            return nazivUstanove;
        }

        /**
         * Sets the value of the nazivUstanove property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivUstanove(String value) {
            this.nazivUstanove = value;
        }

        /**
         * Gets the value of the adresaUstanove property.
         * 
         * @return
         *     possible object is
         *     {@link CTadresa }
         *     
         */
        public CTadresa getAdresaUstanove() {
            return adresaUstanove;
        }

        /**
         * Sets the value of the adresaUstanove property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTadresa }
         *     
         */
        public void setAdresaUstanove(CTadresa value) {
            this.adresaUstanove = value;
        }

        /**
         * Gets the value of the datumIzdavanja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumIzdavanja() {
            return datumIzdavanja;
        }

        /**
         * Sets the value of the datumIzdavanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumIzdavanja(XMLGregorianCalendar value) {
            this.datumIzdavanja = value;
        }

    }

}
