//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.digitalni_sertifikat.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the vaccineisbackend.model.digitalni_sertifikat package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: vaccineisbackend.model.digitalni_sertifikat
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CTinfoSertifikata }
     * 
     */
    public CTinfoSertifikata createCTinfoSertifikata() {
        return new CTinfoSertifikata();
    }

    /**
     * Create an instance of {@link CTtest }
     * 
     */
    public CTtest createCTtest() {
        return new CTtest();
    }

    /**
     * Create an instance of {@link CTvakcinacijaPodaciSertifikat }
     * 
     */
    public CTvakcinacijaPodaciSertifikat createCTvakcinacijaPodaciSertifikat() {
        return new CTvakcinacijaPodaciSertifikat();
    }

    /**
     * Create an instance of {@link ZeleniSertifikat }
     * 
     */
    public ZeleniSertifikat createZeleniSertifikat() {
        return new ZeleniSertifikat();
    }

    /**
     * Create an instance of {@link CTinfoSertifikata.DigitalniPotpis }
     * 
     */
    public CTinfoSertifikata.DigitalniPotpis createCTinfoSertifikataDigitalniPotpis() {
        return new CTinfoSertifikata.DigitalniPotpis();
    }

    /**
     * Create an instance of {@link CTtest.Test }
     * 
     */
    public CTtest.Test createCTtestTest() {
        return new CTtest.Test();
    }

    /**
     * Create an instance of {@link CTvakcinacijaPodaciSertifikat.Doza }
     * 
     */
    public CTvakcinacijaPodaciSertifikat.Doza createCTvakcinacijaPodaciSertifikatDoza() {
        return new CTvakcinacijaPodaciSertifikat.Doza();
    }

}
