//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisemployee.izvestaj.model;

import zajednicko.model.BaseModel;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ftn.uns.ac.rs/zajednicka}STid"/&gt;
 *         &lt;element name="period"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="pocetakPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                   &lt;element name="krajPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brojInteresovanjaImunizacija" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *         &lt;element name="sertifikatInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="brojZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *                   &lt;element name="izdatoZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *         &lt;element name="dozeVakcinaInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="dozaInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                             &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="raspodjelaDoza"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded"&gt;
 *                   &lt;element name="tipVakcineInfo"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datumIzdavanjaIzvjestaja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "period",
    "brojInteresovanjaImunizacija",
    "sertifikatInfo",
    "brojDoza",
    "dozeVakcinaInfo",
    "raspodjelaDoza",
    "datumIzdavanjaIzvjestaja"
})
@XmlRootElement(name = "izvjestaj")
public class Izvjestaj extends BaseModel {

    @XmlElement(required = true)
    protected Izvjestaj.Period period;
    protected int brojInteresovanjaImunizacija;
    @XmlElement(required = true)
    protected SertifikatInfo sertifikatInfo;
    protected int brojDoza;
    @XmlElement(required = true)
    protected DozeVakcinaInfo dozeVakcinaInfo;
    @XmlElement(required = true)
    protected RaspodjelaDoza raspodjelaDoza;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumIzdavanjaIzvjestaja;


    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Period }
     *     
     */
    public Period getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Period }
     *     
     */
    public void setPeriod(Period value) {
        this.period = value;
    }

    /**
     * Gets the value of the brojInteresovanjaImunizacija property.
     * 
     */
    public int getBrojInteresovanjaImunizacija() {
        return brojInteresovanjaImunizacija;
    }

    /**
     * Sets the value of the brojInteresovanjaImunizacija property.
     * 
     */
    public void setBrojInteresovanjaImunizacija(int value) {
        this.brojInteresovanjaImunizacija = value;
    }

    /**
     * Gets the value of the sertifikatInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SertifikatInfo }
     *     
     */
    public SertifikatInfo getSertifikatInfo() {
        return sertifikatInfo;
    }

    /**
     * Sets the value of the sertifikatInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SertifikatInfo }
     *     
     */
    public void setSertifikatInfo(SertifikatInfo value) {
        this.sertifikatInfo = value;
    }

    /**
     * Gets the value of the brojDoza property.
     * 
     */
    public int getBrojDoza() {
        return brojDoza;
    }

    /**
     * Sets the value of the brojDoza property.
     * 
     */
    public void setBrojDoza(int value) {
        this.brojDoza = value;
    }

    /**
     * Gets the value of the dozeVakcinaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DozeVakcinaInfo }
     *     
     */
    public DozeVakcinaInfo getDozeVakcinaInfo() {
        return dozeVakcinaInfo;
    }

    /**
     * Sets the value of the dozeVakcinaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DozeVakcinaInfo }
     *     
     */
    public void setDozeVakcinaInfo(DozeVakcinaInfo value) {
        this.dozeVakcinaInfo = value;
    }

    /**
     * Gets the value of the raspodjelaDoza property.
     * 
     * @return
     *     possible object is
     *     {@link RaspodjelaDoza }
     *     
     */
    public RaspodjelaDoza getRaspodjelaDoza() {
        return raspodjelaDoza;
    }

    /**
     * Sets the value of the raspodjelaDoza property.
     * 
     * @param value
     *     allowed object is
     *     {@link RaspodjelaDoza }
     *     
     */
    public void setRaspodjelaDoza(RaspodjelaDoza value) {
        this.raspodjelaDoza = value;
    }

    /**
     * Gets the value of the datumIzdavanjaIzvjestaja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumIzdavanjaIzvjestaja() {
        return datumIzdavanjaIzvjestaja;
    }

    /**
     * Sets the value of the datumIzdavanjaIzvjestaja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumIzdavanjaIzvjestaja(XMLGregorianCalendar value) {
        this.datumIzdavanjaIzvjestaja = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="dozaInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                   &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dozaInfo"
    })
    public static class DozeVakcinaInfo {

        protected List<DozaInfo> dozaInfo;

        /**
         * Gets the value of the dozaInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dozaInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDozaInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DozaInfo }
         * 
         * 
         */
        public List<DozaInfo> getDozaInfo() {
            if (dozaInfo == null) {
                dozaInfo = new ArrayList<DozaInfo>();
            }
            return this.dozaInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="redniBrojDoze" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *         &lt;element name="brojDatihDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "redniBrojDoze",
            "brojDatihDoza"
        })
        public static class DozaInfo {

            protected int redniBrojDoze;
            protected int brojDatihDoza;

            /**
             * Gets the value of the redniBrojDoze property.
             * 
             */
            public int getRedniBrojDoze() {
                return redniBrojDoze;
            }

            /**
             * Sets the value of the redniBrojDoze property.
             * 
             */
            public void setRedniBrojDoze(int value) {
                this.redniBrojDoze = value;
            }

            /**
             * Gets the value of the brojDatihDoza property.
             * 
             */
            public int getBrojDatihDoza() {
                return brojDatihDoza;
            }

            /**
             * Sets the value of the brojDatihDoza property.
             * 
             */
            public void setBrojDatihDoza(int value) {
                this.brojDatihDoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="pocetakPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *         &lt;element name="krajPerioda" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pocetakPerioda",
        "krajPerioda"
    })
    public static class Period {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar pocetakPerioda;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar krajPerioda;

        /**
         * Gets the value of the pocetakPerioda property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPocetakPerioda() {
            return pocetakPerioda;
        }

        /**
         * Sets the value of the pocetakPerioda property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPocetakPerioda(XMLGregorianCalendar value) {
            this.pocetakPerioda = value;
        }

        /**
         * Gets the value of the krajPerioda property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getKrajPerioda() {
            return krajPerioda;
        }

        /**
         * Sets the value of the krajPerioda property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setKrajPerioda(XMLGregorianCalendar value) {
            this.krajPerioda = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded"&gt;
     *         &lt;element name="tipVakcineInfo"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipVakcineInfo"
    })
    public static class RaspodjelaDoza {

        @XmlElement(required = true)
        protected List<TipVakcineInfo> tipVakcineInfo;

        /**
         * Gets the value of the tipVakcineInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tipVakcineInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTipVakcineInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TipVakcineInfo }
         * 
         * 
         */
        public List<TipVakcineInfo> getTipVakcineInfo() {
            if (tipVakcineInfo == null) {
                tipVakcineInfo = new ArrayList<TipVakcineInfo>();
            }
            return this.tipVakcineInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="nazivProizvodjaca" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="brojDoza" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojDoze"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivProizvodjaca",
            "brojDoza"
        })
        public static class TipVakcineInfo {

            @XmlElement(required = true)
            protected String nazivProizvodjaca;
            protected int brojDoza;

            /**
             * Gets the value of the nazivProizvodjaca property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivProizvodjaca() {
                return nazivProizvodjaca;
            }

            /**
             * Sets the value of the nazivProizvodjaca property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivProizvodjaca(String value) {
                this.nazivProizvodjaca = value;
            }

            /**
             * Gets the value of the brojDoza property.
             * 
             */
            public int getBrojDoza() {
                return brojDoza;
            }

            /**
             * Sets the value of the brojDoza property.
             * 
             */
            public void setBrojDoza(int value) {
                this.brojDoza = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="brojZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
     *         &lt;element name="izdatoZahtjeva" type="{http://www.ftn.uns.ac.rs/zajednicka}STpozitivanBroj"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojZahtjeva",
        "izdatoZahtjeva"
    })
    public static class SertifikatInfo {

        protected int brojZahtjeva;
        protected int izdatoZahtjeva;

        /**
         * Gets the value of the brojZahtjeva property.
         * 
         */
        public int getBrojZahtjeva() {
            return brojZahtjeva;
        }

        /**
         * Sets the value of the brojZahtjeva property.
         * 
         */
        public void setBrojZahtjeva(int value) {
            this.brojZahtjeva = value;
        }

        /**
         * Gets the value of the izdatoZahtjeva property.
         * 
         */
        public int getIzdatoZahtjeva() {
            return izdatoZahtjeva;
        }

        /**
         * Sets the value of the izdatoZahtjeva property.
         * 
         */
        public void setIzdatoZahtjeva(int value) {
            this.izdatoZahtjeva = value;
        }

    }

}
