//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisportal.interesovanje.model;

import zajednicko.model.BaseModel;
import zajednicko.model.CTkontakt;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ftn.uns.ac.rs/zajednicka}STid"/&gt;
 *         &lt;element name="licneInformacije"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="drzavljanstvo"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="Држављанин Републике Србије"/&gt;
 *                         &lt;enumeration value="Страни држављанин са боравком у РС"/&gt;
 *                         &lt;enumeration value="Страни држављанин без боравка у РС"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="jmbg" type="{http://www.ftn.uns.ac.rs/zajednicka}STjmbg"/&gt;
 *                   &lt;element name="ime" type="{http://www.ftn.uns.ac.rs/zajednicka}STime"/&gt;
 *                   &lt;element name="prezime" type="{http://www.ftn.uns.ac.rs/zajednicka}STprezime"/&gt;
 *                   &lt;element name="kontakt" type="{http://www.ftn.uns.ac.rs/zajednicka}CTkontakt"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lokacijaPrimanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STlokacija"/&gt;
 *         &lt;element name="nazivVakcine" type="{http://www.ftn.uns.ac.rs/zajednicka}STodabirVakcine"/&gt;
 *         &lt;element name="davalacKrvi"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Да"/&gt;
 *               &lt;enumeration value="Не"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatum"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "licneInformacije",
    "lokacijaPrimanja",
    "nazivVakcine",
    "davalacKrvi",
    "datum"
})
@XmlRootElement(name = "interesovanje")
public class Interesovanje extends BaseModel {

    @XmlElement(required = true)
    protected Interesovanje.LicneInformacije licneInformacije;
    @XmlElement(required = true)
    protected String lokacijaPrimanja;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String nazivVakcine;
    @XmlElement(required = true)
    protected String davalacKrvi;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datum;

    /**
     * Gets the value of the licneInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link LicneInformacije }
     *     
     */
    public LicneInformacije getLicneInformacije() {
        return licneInformacije;
    }

    /**
     * Sets the value of the licneInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicneInformacije }
     *     
     */
    public void setLicneInformacije(LicneInformacije value) {
        this.licneInformacije = value;
    }

    /**
     * Gets the value of the lokacijaPrimanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLokacijaPrimanja() {
        return lokacijaPrimanja;
    }

    /**
     * Sets the value of the lokacijaPrimanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLokacijaPrimanja(String value) {
        this.lokacijaPrimanja = value;
    }

    /**
     * Gets the value of the nazivVakcine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivVakcine() {
        return nazivVakcine;
    }

    /**
     * Sets the value of the nazivVakcine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivVakcine(String value) {
        this.nazivVakcine = value;
    }

    /**
     * Gets the value of the davalacKrvi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDavalacKrvi() {
        return davalacKrvi;
    }

    /**
     * Sets the value of the davalacKrvi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDavalacKrvi(String value) {
        this.davalacKrvi = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatum(XMLGregorianCalendar value) {
        this.datum = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="drzavljanstvo"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="Држављанин Републике Србије"/&gt;
     *               &lt;enumeration value="Страни држављанин са боравком у РС"/&gt;
     *               &lt;enumeration value="Страни држављанин без боравка у РС"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="jmbg" type="{http://www.ftn.uns.ac.rs/zajednicka}STjmbg"/&gt;
     *         &lt;element name="ime" type="{http://www.ftn.uns.ac.rs/zajednicka}STime"/&gt;
     *         &lt;element name="prezime" type="{http://www.ftn.uns.ac.rs/zajednicka}STprezime"/&gt;
     *         &lt;element name="kontakt" type="{http://www.ftn.uns.ac.rs/zajednicka}CTkontakt"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "drzavljanstvo",
        "jmbg",
        "ime",
        "prezime",
        "kontakt"
    })
    public static class LicneInformacije  {

        @XmlElement(required = true)
        protected String drzavljanstvo;
        @XmlElement(required = true)
        protected String jmbg;
        @XmlElement(required = true)
        protected String ime;
        @XmlElement(required = true)
        protected String prezime;
        @XmlElement(required = true)
        protected CTkontakt kontakt;

        /**
         * Gets the value of the drzavljanstvo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDrzavljanstvo() {
            return drzavljanstvo;
        }

        /**
         * Sets the value of the drzavljanstvo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDrzavljanstvo(String value) {
            this.drzavljanstvo = value;
        }

        /**
         * Gets the value of the jmbg property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJmbg() {
            return jmbg;
        }

        /**
         * Sets the value of the jmbg property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJmbg(String value) {
            this.jmbg = value;
        }

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIme(String value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezime(String value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the kontakt property.
         * 
         * @return
         *     possible object is
         *     {@link CTkontakt }
         *     
         */
        public CTkontakt getKontakt() {
            return kontakt;
        }

        /**
         * Sets the value of the kontakt property.
         * 
         * @param value
         *     allowed object is
         *     {@link CTkontakt }
         *     
         */
        public void setKontakt(CTkontakt value) {
            this.kontakt = value;
        }

    }

}
