//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 01:51:16 AM CET 
//


package vaccineisportal.zeleni_sertifikat_bridge.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for CTtest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CTtest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="test"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="tipTesta"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="SARS-CoV-2 RT Real-time PCR"/&gt;
 *                         &lt;enumeration value="SARS-CoV-2 Ag-RDT (Antigen Rapid Detection test)"/&gt;
 *                         &lt;enumeration value="SARS-CoV-2 RBD S-Protein Immunoglobulin G (lgG) test"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="vrstaUzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="proizvodjacTesta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="datumVremeUzorkovanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatumVrijeme"/&gt;
 *                   &lt;element name="datumVremeRezultata" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatumVrijeme"/&gt;
 *                   &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CTtest", propOrder = {
    "test"
})
public class CTtest {

    protected List<Test> test;

    /**
     * Gets the value of the test property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the test property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Test }
     * 
     * 
     */
    public List<Test> getTest() {
        if (test == null) {
            test = new ArrayList<Test>();
        }
        return this.test;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="tipTesta"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="SARS-CoV-2 RT Real-time PCR"/&gt;
     *               &lt;enumeration value="SARS-CoV-2 Ag-RDT (Antigen Rapid Detection test)"/&gt;
     *               &lt;enumeration value="SARS-CoV-2 RBD S-Protein Immunoglobulin G (lgG) test"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="vrstaUzorka" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="proizvodjacTesta" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="datumVremeUzorkovanja" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatumVrijeme"/&gt;
     *         &lt;element name="datumVremeRezultata" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatumVrijeme"/&gt;
     *         &lt;element name="rezultat" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="laboratorija" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipTesta",
        "vrstaUzorka",
        "proizvodjacTesta",
        "datumVremeUzorkovanja",
        "datumVremeRezultata",
        "rezultat",
        "laboratorija"
    })
    public static class Test {

        @XmlElement(required = true)
        protected String tipTesta;
        @XmlElement(required = true)
        protected String vrstaUzorka;
        @XmlElement(required = true)
        protected String proizvodjacTesta;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datumVremeUzorkovanja;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datumVremeRezultata;
        @XmlElement(required = true)
        protected String rezultat;
        @XmlElement(required = true)
        protected String laboratorija;

        /**
         * Gets the value of the tipTesta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipTesta() {
            return tipTesta;
        }

        /**
         * Sets the value of the tipTesta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipTesta(String value) {
            this.tipTesta = value;
        }

        /**
         * Gets the value of the vrstaUzorka property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVrstaUzorka() {
            return vrstaUzorka;
        }

        /**
         * Sets the value of the vrstaUzorka property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVrstaUzorka(String value) {
            this.vrstaUzorka = value;
        }

        /**
         * Gets the value of the proizvodjacTesta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProizvodjacTesta() {
            return proizvodjacTesta;
        }

        /**
         * Sets the value of the proizvodjacTesta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProizvodjacTesta(String value) {
            this.proizvodjacTesta = value;
        }

        /**
         * Gets the value of the datumVremeUzorkovanja property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumVremeUzorkovanja() {
            return datumVremeUzorkovanja;
        }

        /**
         * Sets the value of the datumVremeUzorkovanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumVremeUzorkovanja(XMLGregorianCalendar value) {
            this.datumVremeUzorkovanja = value;
        }

        /**
         * Gets the value of the datumVremeRezultata property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatumVremeRezultata() {
            return datumVremeRezultata;
        }

        /**
         * Sets the value of the datumVremeRezultata property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatumVremeRezultata(XMLGregorianCalendar value) {
            this.datumVremeRezultata = value;
        }

        /**
         * Gets the value of the rezultat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRezultat() {
            return rezultat;
        }

        /**
         * Sets the value of the rezultat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRezultat(String value) {
            this.rezultat = value;
        }

        /**
         * Gets the value of the laboratorija property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLaboratorija() {
            return laboratorija;
        }

        /**
         * Sets the value of the laboratorija property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLaboratorija(String value) {
            this.laboratorija = value;
        }

    }

}
