//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.17 at 02:56:16 AM CET
//


package vaccineisportal.zeleni_sertifikat_bridge.model;

import zajednicko.model.BaseModel;
import zajednicko.model.CTpodnosilacZahtjeva;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.ftn.uns.ac.rs/zajednicka}STid"/&gt;
 *         &lt;element name="qrKod" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="podaciVakcinisanog" type="{http://www.ftn.uns.ac.rs/zajednicka}CTpodnosilacZahtjeva"/&gt;
 *         &lt;element name="vakcinacija" type="{http://www.ftn.uns.ac.rs/digitalni-sertifikat}CTvakcinacijaPodaciSertifikat"/&gt;
 *         &lt;element name="testovi" type="{http://www.ftn.uns.ac.rs/digitalni-sertifikat}CTtest"/&gt;
 *         &lt;element name="infoSertifikata" type="{http://www.ftn.uns.ac.rs/digitalni-sertifikat}CTinfoSertifikata"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="brojSertifikata" use="required" type="{http://www.ftn.uns.ac.rs/zajednicka}STbrojSertifikata" /&gt;
 *       &lt;attribute name="datumVrijemeIzdavanja" use="required" type="{http://www.ftn.uns.ac.rs/zajednicka}STdatumVrijeme" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "qrKod",
        "podaciVakcinisanog",
        "vakcinacija",
        "testovi",
        "infoSertifikata"
})
@XmlRootElement(name = "zeleniSertifikat")
public class ZeleniSertifikat extends BaseModel {

    @XmlElement(required = true)
    protected Object qrKod;
    @XmlElement(required = true)
    protected CTpodnosilacZahtjeva podaciVakcinisanog;
    @XmlElement(required = true)
    protected CTvakcinacijaPodaciSertifikat vakcinacija;
    @XmlElement(required = true)
    protected CTtest testovi;
    @XmlElement(required = true)
    protected CTinfoSertifikata infoSertifikata;
    @XmlAttribute(name = "brojSertifikata", required = true)
    protected String brojSertifikata;
    @XmlAttribute(name = "datumVrijemeIzdavanja", required = true)
    protected XMLGregorianCalendar datumVrijemeIzdavanja;

    /**
     * Gets the value of the qrKod property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getQrKod() {
        return qrKod;
    }

    /**
     * Sets the value of the qrKod property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setQrKod(Object value) {
        this.qrKod = value;
    }

    /**
     * Gets the value of the podaciVakcinisanog property.
     *
     * @return
     *     possible object is
     *     {@link CTpodnosilacZahtjeva }
     *
     */
    public CTpodnosilacZahtjeva getPodaciVakcinisanog() {
        return podaciVakcinisanog;
    }

    /**
     * Sets the value of the podaciVakcinisanog property.
     *
     * @param value
     *     allowed object is
     *     {@link CTpodnosilacZahtjeva }
     *
     */
    public void setPodaciVakcinisanog(CTpodnosilacZahtjeva value) {
        this.podaciVakcinisanog = value;
    }

    /**
     * Gets the value of the vakcinacija property.
     *
     * @return
     *     possible object is
     *     {@link CTvakcinacijaPodaciSertifikat }
     *
     */
    public CTvakcinacijaPodaciSertifikat getVakcinacija() {
        return vakcinacija;
    }

    /**
     * Sets the value of the vakcinacija property.
     *
     * @param value
     *     allowed object is
     *     {@link CTvakcinacijaPodaciSertifikat }
     *
     */
    public void setVakcinacija(CTvakcinacijaPodaciSertifikat value) {
        this.vakcinacija = value;
    }

    /**
     * Gets the value of the testovi property.
     *
     * @return
     *     possible object is
     *     {@link CTtest }
     *
     */
    public CTtest getTestovi() {
        return testovi;
    }

    /**
     * Sets the value of the testovi property.
     *
     * @param value
     *     allowed object is
     *     {@link CTtest }
     *
     */
    public void setTestovi(CTtest value) {
        this.testovi = value;
    }

    /**
     * Gets the value of the infoSertifikata property.
     *
     * @return
     *     possible object is
     *     {@link CTinfoSertifikata }
     *
     */
    public CTinfoSertifikata getInfoSertifikata() {
        return infoSertifikata;
    }

    /**
     * Sets the value of the infoSertifikata property.
     *
     * @param value
     *     allowed object is
     *     {@link CTinfoSertifikata }
     *
     */
    public void setInfoSertifikata(CTinfoSertifikata value) {
        this.infoSertifikata = value;
    }

    /**
     * Gets the value of the brojSertifikata property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBrojSertifikata() {
        return brojSertifikata;
    }

    /**
     * Sets the value of the brojSertifikata property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBrojSertifikata(String value) {
        this.brojSertifikata = value;
    }

    /**
     * Gets the value of the datumVrijemeIzdavanja property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDatumVrijemeIzdavanja() {
        return datumVrijemeIzdavanja;
    }

    /**
     * Sets the value of the datumVrijemeIzdavanja property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDatumVrijemeIzdavanja(XMLGregorianCalendar value) {
        this.datumVrijemeIzdavanja = value;
    }

}
