//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.15 at 09:34:48 PM CET 
//


package vaccineisportal.authentication.dto.UserRegistration;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.korisnik
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserRegistrationDTO }
     * 
     */
    public UserRegistrationDTO createUserRegistrationDTO() {
        return new UserRegistrationDTO();
    }

}
